name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PanagiotisDrakatos
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          config_display: large

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PanagiotisDrakatos
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_from: 200
          config_timezone: Europe/Athens

  stars:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PanagiotisDrakatos
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 4

  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PanagiotisDrakatos
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: PanagiotisDrakatos
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
